FROM library/devel:0.6-cuda13.1.1

RUN apt-get update && apt-get install -y --no-install-recommends zsh locales \
    clang libclang-dev libgraphite2-3 imagemagick ghostscript\
    && locale-gen en_US.UTF-8 \
    && echo 'emulate sh -c ". /etc/profile"' >> /etc/zsh/zprofile # Source /etc/profile.d/container-env.sh for zsh login shells

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV EDITOR=nvim

# Install Oh-My-Zsh and Powerlevel10k
ENV ZSH="/usr/local/bin/ohmyzsh"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH}/custom/themes/powerlevel10k 
ENV SHELL=/usr/bin/zsh

# Install Claude Code
RUN curl -fsSL "https://claude.ai/install.sh" | bash \
    && cp /root/.local/bin/claude /usr/local/bin/claude \
    && chmod 755 /usr/local/bin/claude

# Install Neovim
ARG NVIM_VERSION=0.11.6
RUN curl -fsSL "https://github.com/neovim/neovim/releases/download/v${NVIM_VERSION}/nvim-linux-x86_64.tar.gz" \
    | tar -xz -C /opt \
    && ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim

# Install Cargo and Rustup
ENV RUSTUP_HOME=/opt/cargo
ENV CARGO_HOME=/opt/cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && chmod -R 777 /opt/cargo

# Install tree-sitter-cli
RUN /opt/cargo/bin/cargo install --locked tree-sitter-cli

# Install tectonic
RUN curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh \
    && mv tectonic /usr/local/bin/tectonic \
    && chmod 755 /usr/local/bin/tectonic

# Install Lazygit (After Ubuntu 26.04 we can remove this and install from apt)
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')\
    && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"\
    && tar xf lazygit.tar.gz lazygit\
    && install lazygit -D -t /usr/local/bin/

RUN sed -i '/^auth.*required.*pam_shells.so/a auth       sufficient pam_usertype.so isregular' /etc/pam.d/chsh

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/bin/zsh"]
